add fail-safe in makefile
 if lua/osascript not found, make continues

diff --git a/unwired/asuno-light/Makefile b/unwired/asuno-light/Makefile
--- a/unwired/asuno-light/Makefile
+++ b/unwired/asuno-light/Makefile
@@ -22,7 +22,7 @@ root:
 	[ "x`cat /tmp/unwired_last_conf`" != "x$$CONF" ] && make clean_no_hex; \
 	echo $$CONF > /tmp/unwired_last_conf
 	make -j5 TARGET=unwired BOARD=$(BOARD)/$(CPU) -f makefiles/Makefile.root
-	arm-none-eabi-size root.elf  | grep -v text | lua ../../tools/mem_used.lua 125000 20000
+	arm-none-eabi-size root.elf  | grep -v text | lua ../../tools/mem_used.lua 125000 20000 || echo "------ Lua not found ------"
 	../bootloader/generate-metadata/generate-metadata root.bin 0x0 0x01FF0001 1
 	srec_cat firmware-metadata.bin -binary root.bin -binary -offset 0x100 -o root-ota-image.bin -binary
 	srec_cat ../bootloader/bootloader.hex -intel -crop 0x0 0x2000 0x1FFA8 0x20000 root-ota-image.bin -binary -offset 0x2000 -crop 0x2000 0x1B000 -o root-firmware.hex -intel
@@ -34,7 +34,7 @@ light: net-bootloader
 	[ "x`cat /tmp/unwired_last_conf`" != "x$$CONF" ] && make clean; \
 	echo $$CONF > /tmp/unwired_last_conf
 	make -j5 TARGET=unwired BOARD=$(BOARD)/$(CPU) -f makefiles/Makefile.light
-	arm-none-eabi-size light.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000
+	arm-none-eabi-size light.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000 || echo "------ Lua not found ------"
 	../bootloader/generate-metadata/generate-metadata light.bin 0x0 0x01A00001 1
 	srec_cat firmware-metadata.bin -binary light.bin -binary -offset 0x100 -o light-ota-image.bin -binary
 	srec_cat ../bootloader/bootloader.hex -intel -crop 0x0 0x2000 0x1FFA8 0x20000 light-ota-image.bin -binary -offset 0x2000 -crop 0x2000 0x1B000 -o light-firmware.hex -intel
@@ -73,7 +73,7 @@ light-fb: light-CLEAN
 light-f: light-CLEAN
 	/Applications/ti/Uniflash/flash_cc1310.sh light-firmware.hex && \
 	osascript -e 'display notification with title "Flash asuno/light" subtitle "Success"' || \
-	osascript -e 'display notification with title "Flash asuno/light" subtitle "FAIL"'
+	osascript -e 'display notification with title "Flash asuno/light" subtitle "FAIL"' || echo "osascript not found"
 
 light-ota: light
 	scp light-ota-image.bin root@192.168.20.187:/root/unwired_smarthome
@@ -85,7 +85,7 @@ root-fb: root-CLEAN
 root-f: root-CLEAN
 	/Applications/ti/Uniflash/flash_cc1310.sh root-firmware.hex && \
 	osascript -e 'display notification with title "Flash asuno/root" subtitle "Success"' || \
-	osascript -e 'display notification with title "Flash asuno/root" subtitle "FAIL"'
+	osascript -e 'display notification with title "Flash asuno/root" subtitle "FAIL"' || echo "osascript not found"
 
 serial:
 	../../tools/sky/serialdump-macos -b115200 /dev/tty.usbserial-* || ../../tools/sky/serialdump-macos -b115200 /dev/tty.SLAB_USBtoUART
diff --git a/unwired/smarthome/Makefile b/unwired/smarthome/Makefile
--- a/unwired/smarthome/Makefile
+++ b/unwired/smarthome/Makefile
@@ -28,7 +28,7 @@ button: net-bootloader-clean
 	[ "x`cat /tmp/unwired_last_conf`" != "x$$CONF" ] && make clean_no_hex; \
 	echo $$CONF > /tmp/unwired_last_conf
 	make -j5 TARGET=unwired BOARD=$(BOARD)/$(CPU) -f makefiles/Makefile.button
-	arm-none-eabi-size button.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000
+	arm-none-eabi-size button.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000 || echo "------ Lua not found ------"
 	../bootloader/generate-metadata/generate-metadata button.bin 0x0 0x00A10001 1
 	srec_cat firmware-metadata.bin -binary button.bin -binary -offset 0x100 -o button-ota-image.bin -binary
 	srec_cat ../bootloader/bootloader.hex -intel -crop 0x0 0x2000 0x1FFA8 0x20000 button-ota-image.bin -binary -offset 0x2000 -crop 0x2000 0x1B000 -o button-firmware.hex -intel
@@ -40,7 +40,7 @@ root: net-bootloader-clean
 	[ "x`cat /tmp/unwired_last_conf`" != "x$$CONF" ] && make clean_no_hex; \
 	echo $$CONF > /tmp/unwired_last_conf
 	make -j5 TARGET=unwired BOARD=$(BOARD)/$(CPU) -f makefiles/Makefile.root
-	arm-none-eabi-size root.elf  | grep -v text | lua ../../tools/mem_used.lua 125000 20000
+	arm-none-eabi-size root.elf  | grep -v text | lua ../../tools/mem_used.lua 125000 20000 || echo "------ Lua not found ------"
 	../bootloader/generate-metadata/generate-metadata root.bin 0x0 0x00FF0001 1
 	srec_cat firmware-metadata.bin -binary root.bin -binary -offset 0x100 -o root-ota-image.bin -binary
 	srec_cat ../bootloader/bootloader.hex -intel -crop 0x0 0x2000 0x1FFA8 0x20000 root-ota-image.bin -binary -offset 0x2000 -crop 0x2000 0x1B000 -o root-firmware.hex -intel
@@ -52,7 +52,7 @@ relay: net-bootloader-clean
 	[ "x`cat /tmp/unwired_last_conf`" != "x$$CONF" ] && make clean_no_hex; \
 	echo $$CONF > /tmp/unwired_last_conf
 	make -j5 TARGET=unwired BOARD=$(BOARD)/$(CPU) -f makefiles/Makefile.relay
-	arm-none-eabi-size relay.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000
+	arm-none-eabi-size relay.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000 || echo "------ Lua not found ------"
 	../bootloader/generate-metadata/generate-metadata relay.bin 0x0 0x00A20001 1
 	srec_cat firmware-metadata.bin -binary relay.bin -binary -offset 0x100 -o relay-ota-image.bin -binary
 	srec_cat ../bootloader/bootloader.hex -intel -crop 0x0 0x2000 0x1FFA8 0x20000 relay-ota-image.bin -binary -offset 0x2000 -crop 0x2000 0x1B000 -o relay-firmware.hex -intel
@@ -64,7 +64,7 @@ dimmer: net-bootloader-clean
 	[ "x`cat /tmp/unwired_last_conf`" != "x$$CONF" ] && make clean; \
 	echo $$CONF > /tmp/unwired_last_conf
 	make -j5 TARGET=unwired BOARD=$(BOARD)/$(CPU) -f makefiles/Makefile.dimmer
-	arm-none-eabi-size dimmer.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000
+	arm-none-eabi-size dimmer.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000 || echo "------ Lua not found ------"
 	../bootloader/generate-metadata/generate-metadata dimmer.bin 0x0 0x00A30001 1
 	srec_cat firmware-metadata.bin -binary dimmer.bin -binary -offset 0x100 -o dimmer-ota-image.bin -binary
 	srec_cat ../bootloader/bootloader.hex -intel -crop 0x0 0x2000 0x1FFA8 0x20000 dimmer-ota-image.bin -binary -offset 0x2000 -crop 0x2000 0x1B000 -o dimmer-firmware.hex -intel
@@ -76,8 +76,7 @@ motionsensor: net-bootloader-clean
 	[ "x`cat /tmp/unwired_last_conf`" != "x$$CONF" ] && make clean; \
 	echo $$CONF > /tmp/unwired_last_conf
 	make -j5 TARGET=unwired BOARD=$(BOARD)/$(CPU) -f makefiles/Makefile.motionsensor
-	arm-none-eabi-size motionsensor.elf | grep -v text > /tmp/size.tmp
-	lua ../../tools/mem_used.lua /tmp/size.tmp 125000 20000
+	arm-none-eabi-size motionsensor.elf | grep -v text | lua ../../tools/mem_used.lua 125000 20000 || echo "------ Lua not found ------"
 	../bootloader/generate-metadata/generate-metadata motionsensor.bin 0x0 0x00A40001 1
 	srec_cat firmware-metadata.bin -binary motionsensor.bin -binary -offset 0x100 -o motionsensor-ota-image.bin -binary
 	srec_cat ../bootloader/bootloader.hex -intel -crop 0x0 0x2000 0x1FFA8 0x20000 motionsensor-ota-image.bin -binary -offset 0x2000 -crop 0x2000 0x1B000 -o motionsensor-firmware.hex -intel
